version: "3.8"
services:
  api:
    container_name: clean-node-api
    build:
      context: .
      dockerfile: Dockerfile
    image: clean-node-api  
    ports:
      - "3000:3000"
    volumes:
      - ./dist:/usr/src/app/dist
    command: npm start  
    